import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { ThemeToggle } from "@/components/theme-toggle";
import Navbar from "@/components/nav/Navbar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} h-full antialiased max-w-7xl mx-auto`}
      // className={`${outfit.variable} font-sans`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
       <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
